/**
 * src/app/api/projects/[id]/scaffold/route.ts
 *
 * POST /api/projects/[id]/scaffold
 *
 * Generates platform-specific initial files for a project and commits
 * them atomically to GitHub via the Tree API.
 *
 * Called from:
 *   - /projects/[id]/onboarding  — after wizard step "Platform confirmed"
 *   - Internal: orchestration tick (idempotent — safe to re-run)
 *
 * Auth: user JWT OR internal X-Buildos-Secret header
 *
 * Idempotent: uses project.scaffold_committed_at to skip if already done.
 * Pass ?force=true to re-scaffold (e.g. after project_type change).
 */

import { NextRequest, NextResponse } from 'next/server'
import { createAdminSupabaseClient, createServerSupabaseClient } from '@/lib/supabase/server'
import { getPlatformContext } from '@/lib/platform-registry'
import { generateScaffold } from '@/lib/scaffold-generator'
import type { ScaffoldFile } from '@/lib/scaffold-generator'

// ─── GitHub Tree API commit helper ────────────────────────────────────────────

async function getGitHubToken(): Promise<string> {
  // Reuse the existing GitHub App installation token logic from the generate route
  const { createAppToken } = await import('@/lib/github-app')
  return createAppToken()
}

async function commitScaffoldToGitHub(
  files: ScaffoldFile[],
  repoOwner: string,
  repoName: string,
  branch: string,
  projectName: string,
  token: string,
): Promise<{ sha: string; url: string }> {
  const apiBase = `https://api.github.com/repos/${repoOwner}/${repoName}`
  const headers = {
    Authorization: `token ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  }

  // 1. Get current HEAD SHA
  const refRes = await fetch(`${apiBase}/git/ref/heads/${branch}`, { headers })
  if (!refRes.ok) throw new Error(`Failed to get branch ref: ${await refRes.text()}`)
  const { object: { sha: headSha } } = await refRes.json()

  // 2. Get base tree SHA
  const commitRes = await fetch(`${apiBase}/git/commits/${headSha}`, { headers })
  if (!commitRes.ok) throw new Error(`Failed to get commit: ${await commitRes.text()}`)
  const { tree: { sha: baseTreeSha } } = await commitRes.json()

  // 3. Build tree objects
  const treeObjects = files.map(file => ({
    path: file.path,
    mode: '100644',
    type: 'blob',
    content: file.content,
  }))

  // 4. Create tree
  const treeRes = await fetch(`${apiBase}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ base_tree: baseTreeSha, tree: treeObjects }),
  })
  if (!treeRes.ok) throw new Error(`Failed to create tree: ${await treeRes.text()}`)
  const { sha: newTreeSha } = await treeRes.json()

  // 5. Create commit
  const newCommitRes = await fetch(`${apiBase}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      message: `scaffold: initialize ${projectName} platform environment\n\nAuto-generated by BuildOS scaffold engine.\nPlatform: ${projectName}`,
      tree: newTreeSha,
      parents: [headSha],
    }),
  })
  if (!newCommitRes.ok) throw new Error(`Failed to create commit: ${await newCommitRes.text()}`)
  const { sha: newCommitSha, html_url } = await newCommitRes.json()

  // 6. Update branch ref
  const updateRes = await fetch(`${apiBase}/git/refs/heads/${branch}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ sha: newCommitSha, force: false }),
  })
  if (!updateRes.ok) throw new Error(`Failed to update ref: ${await updateRes.text()}`)

  return { sha: newCommitSha, url: html_url }
}

// ─── Route handler ─────────────────────────────────────────────────────────────

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const admin = createAdminSupabaseClient()

  try {
    // ── Auth ──────────────────────────────────────────────────────────────────
    const internalSecret = request.headers.get('X-Buildos-Secret')
    const BUILDOS_INTERNAL_SECRET = process.env.BUILDOS_INTERNAL_SECRET || process.env.BUILDOS_SECRET || ''

    if (!internalSecret || internalSecret !== BUILDOS_INTERNAL_SECRET) {
      const supabase = await createServerSupabaseClient()
      const { data: { user }, error } = await supabase.auth.getUser()
      if (error || !user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
      }
    }

    const force = request.nextUrl.searchParams.get('force') === 'true'

    // ── Fetch project ────────────────────────────────────────────────────────
    const { data: project, error: projectError } = await admin
      .from('projects')
      .select('id, name, description, project_type, scaffold_committed_at')
      .eq('id', params.id)
      .single()

    if (projectError || !project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    // ── Idempotency check ────────────────────────────────────────────────────
    if (project.scaffold_committed_at && !force) {
      return NextResponse.json({
        data: { skipped: true, reason: 'Scaffold already committed', committed_at: project.scaffold_committed_at }
      })
    }

    // ── Resolve platform context ─────────────────────────────────────────────
    const platformCtx = getPlatformContext(project.project_type)
    console.log(`[scaffold] Project ${project.id} → platform: ${platformCtx.name}`)

    // ── Generate scaffold files ──────────────────────────────────────────────
    const files = generateScaffold(platformCtx, project.name)
    console.log(`[scaffold] Generated ${files.length} files for ${project.name}`)

    // ── Fetch GitHub repo config from project integrations ───────────────────
    const { data: integration } = await admin
      .from('project_integrations')
      .select('*')
      .eq('project_id', params.id)
      .eq('provider', 'github')
      .maybeSingle()

    if (!integration) {
      return NextResponse.json(
        { error: 'No GitHub integration found for this project. Connect GitHub first.' },
        { status: 422 }
      )
    }

    const repoOwner = integration.repo_owner ?? process.env.GITHUB_REPO_OWNER
    const repoName  = integration.repo_name  ?? process.env.GITHUB_REPO_NAME
    const branch    = integration.repo_branch ?? process.env.GITHUB_REPO_BRANCH ?? 'main'

    if (!repoOwner || !repoName) {
      return NextResponse.json(
        { error: 'GitHub repo owner/name not configured for this project.' },
        { status: 422 }
      )
    }

    // ── Commit to GitHub ─────────────────────────────────────────────────────
    const token = await getGitHubToken()
    const { sha, url } = await commitScaffoldToGitHub(
      files, repoOwner, repoName, branch, project.name, token
    )

    console.log(`[scaffold] Committed scaffold: ${sha}`)

    // ── Mark scaffold committed ───────────────────────────────────────────────
    await admin
      .from('projects')
      .update({ scaffold_committed_at: new Date().toISOString() })
      .eq('id', params.id)

    // ── Write audit log ───────────────────────────────────────────────────────
    await admin.from('audit_logs').insert({
      project_id: params.id,
      actor: 'system:scaffold',
      action: 'scaffold.committed',
      metadata: {
        platform_type: project.project_type,
        platform_name: platformCtx.name,
        files_committed: files.map(f => f.path),
        commit_sha: sha,
        commit_url: url,
      },
    }).throwOnError()

    return NextResponse.json({
      data: {
        project_id: params.id,
        platform: platformCtx.name,
        files_committed: files.length,
        file_paths: files.map(f => f.path),
        commit_sha: sha,
        commit_url: url,
      }
    })

  } catch (err) {
    const msg = String(err)
    console.error('[scaffold] Error:', msg)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}

// GET — check scaffold status
export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const admin = createAdminSupabaseClient()
  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: project } = await admin
    .from('projects')
    .select('id, name, project_type, scaffold_committed_at')
    .eq('id', params.id)
    .single()

  if (!project) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const platformCtx = getPlatformContext(project.project_type)

  return NextResponse.json({
    data: {
      project_id: project.id,
      project_name: project.name,
      project_type: project.project_type,
      platform_name: platformCtx.name,
      scaffold_committed: !!project.scaffold_committed_at,
      scaffold_committed_at: project.scaffold_committed_at,
      would_generate: generateScaffold(platformCtx, project.name).map(f => f.path),
    }
  })
}
