/**
 * src/app/api/projects/[id]/scaffold/route.ts
 *
 * POST /api/projects/[id]/scaffold
 *
 * Generates platform-specific initial files for a project and commits
 * them atomically to GitHub via the Tree API.
 *
 * Called from:
 *   - /projects/[id]/onboarding — after wizard step "Platform confirmed"
 *   - Manual trigger for testing
 *
 * Auth: user JWT OR internal X-Buildos-Secret header
 * Idempotent: skips if scaffold_committed_at is set (unless ?force=true)
 */

import { NextRequest, NextResponse } from 'next/server'
import { createAdminSupabaseClient, createServerSupabaseClient } from '@/lib/supabase/server'
import { getPlatformContext } from '@/lib/platform-registry'
import { generateScaffold } from '@/lib/scaffold-generator'
import { commitFilesToGitHub } from '@/lib/github-commit'

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const admin = createAdminSupabaseClient()

  try {
    // ── Auth ──────────────────────────────────────────────────────────────────
    const internalSecret = request.headers.get('X-Buildos-Secret')
    const BUILDOS_INTERNAL_SECRET = process.env.BUILDOS_INTERNAL_SECRET || process.env.BUILDOS_SECRET || ''

    if (!internalSecret || internalSecret !== BUILDOS_INTERNAL_SECRET) {
      const supabase = await createServerSupabaseClient()
      const { data: { user }, error } = await supabase.auth.getUser()
      if (error || !user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
      }
    }

    const force = request.nextUrl.searchParams.get('force') === 'true'

    // ── Fetch project ────────────────────────────────────────────────────────
    const { data: project, error: projectError } = await admin
      .from('projects')
      .select('id, name, description, project_type, scaffold_committed_at')
      .eq('id', params.id)
      .single()

    if (projectError || !project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    // ── Idempotency check ────────────────────────────────────────────────────
    if ((project as Record<string, unknown>).scaffold_committed_at && !force) {
      return NextResponse.json({
        data: { skipped: true, reason: 'Scaffold already committed', committed_at: (project as Record<string, unknown>).scaffold_committed_at }
      })
    }

    // ── Resolve platform context ─────────────────────────────────────────────
    const platformCtx = getPlatformContext((project as Record<string, unknown>).project_type as string)
    console.log(`[scaffold] Project ${project.id} → platform: ${platformCtx.name}`)

    // ── Resolve per-project GitHub repo from deployment_targets ──────────────
    // Phase 5: scaffold must commit to the project's OWN repo, not the monorepo.
    // The target_config.github_repo_fullname is written by /api/bootstrap/project.
    let repoOwner: string | undefined
    let repoName: string | undefined
    let repoInstallationId: string | undefined

    const { data: deployTarget } = await admin
      .from('deployment_targets')
      .select('target_config')
      .eq('project_id', params.id)
      .eq('provider', 'vercel')
      .eq('status', 'live')
      .maybeSingle()

    if (deployTarget?.target_config) {
      const cfg = deployTarget.target_config as Record<string, unknown>
      const fullName = cfg.github_repo_fullname as string | undefined
      if (fullName && fullName.includes('/')) {
        const [o, r] = fullName.split('/')
        repoOwner = o
        repoName = r
        console.log(`[scaffold] Target repo resolved: ${fullName}`)
      }
      // Installation ID stored during bootstrap (github_installation_id in config)
      repoInstallationId = (cfg.github_installation_id as string | undefined)
        ?? process.env.GITHUB_INSTALLATION_ID
        ?? process.env.GITHUB_APP_INSTALLATION_ID
    }

    // ── Generate scaffold files ──────────────────────────────────────────────
    const files = generateScaffold(platformCtx, project.name)
    console.log(`[scaffold] Generated ${files.length} files for ${project.name}`)

    // ── Commit to the per-project repo ───────────────────────────────────────
    // noPathPrefix: true — project repos have no monorepo prefix (unlike build-os monorepo).
    const commitResult = await commitFilesToGitHub(
      files.map(f => ({ path: f.path, content: f.content })),
      `scaffold: initialize ${project.name} platform environment (${platformCtx.name})\n\nAuto-generated by BuildOS scaffold engine based on project_type="${(project as Record<string, unknown>).project_type}".`,
      undefined,
      repoOwner && repoName
        ? { owner: repoOwner, repo: repoName, installationId: repoInstallationId, noPathPrefix: true }
        : { noPathPrefix: true },
    )

    if (!commitResult.success) {
      return NextResponse.json(
        { error: `GitHub commit failed: ${commitResult.error}` },
        { status: 500 }
      )
    }

    console.log(`[scaffold] Committed: ${commitResult.commitSha}`)

    // ── Mark scaffold committed ───────────────────────────────────────────────
    await admin
      .from('projects')
      .update({ scaffold_committed_at: new Date().toISOString() } as Record<string, unknown>)
      .eq('id', params.id)

    // ── Write audit log ───────────────────────────────────────────────────────
    await admin.from('audit_logs').insert({
      project_id: params.id,
      actor: 'system:scaffold',
      action: 'scaffold.committed',
      metadata: {
        platform_type: (project as Record<string, unknown>).project_type,
        platform_name: platformCtx.name,
        files_committed: files.map(f => f.path),
        commit_sha: commitResult.commitSha,
        commit_url: commitResult.commitUrl,
        target_repo: repoOwner && repoName ? `${repoOwner}/${repoName}` : 'monorepo-fallback',
      },
    })

    return NextResponse.json({
      data: {
        project_id: params.id,
        platform: platformCtx.name,
        files_committed: files.length,
        file_paths: files.map(f => f.path),
        commit_sha: commitResult.commitSha,
        commit_url: commitResult.commitUrl,
        target_repo: repoOwner && repoName ? `${repoOwner}/${repoName}` : 'monorepo-fallback',
      }
    })

  } catch (err) {
    const msg = String(err)
    console.error('[scaffold] Error:', msg)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}

// GET — check scaffold status
export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const admin = createAdminSupabaseClient()
  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: project } = await admin
    .from('projects')
    .select('id, name, project_type, scaffold_committed_at')
    .eq('id', params.id)
    .single()

  if (!project) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const platformCtx = getPlatformContext((project as Record<string, unknown>).project_type as string)

  return NextResponse.json({
    data: {
      project_id: project.id,
      project_name: project.name,
      project_type: (project as Record<string, unknown>).project_type,
      platform_name: platformCtx.name,
      scaffold_committed: !!(project as Record<string, unknown>).scaffold_committed_at,
      scaffold_committed_at: (project as Record<string, unknown>).scaffold_committed_at,
      would_generate: generateScaffold(platformCtx, project.name).map(f => f.path),
    }
  })
}
