/**
 * POST /api/documents — create or update a project document
 * GET /api/documents?project_id= — list all documents for a project
 *
 * Documents are auto-generated by the Documentation Engineer agent
 * after agent outputs are received. They can also be created manually.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient, createAdminSupabaseClient } from '@/lib/supabase/server'
import { writeAuditLog } from '@/lib/execution'

const ALLOWED_DOC_TYPES = [
  'prd', 'architecture', 'adr', 'data_model', 'api_contract',
  'automation', 'cost_model', 'qa_report', 'runbook', 'other',
] as const

export async function GET(request: NextRequest) {
  try {
    const supabase = await createServerSupabaseClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const projectId = searchParams.get('project_id')
    const docType   = searchParams.get('doc_type')

    if (!projectId) {
      return NextResponse.json({ error: 'project_id required' }, { status: 400 })
    }

    let query = supabase
      .from('documents')
      .select('id, doc_type, title, status, version, content, owner_agent_role, created_by, created_at, updated_at')
      .eq('project_id', projectId)
      .order('updated_at', { ascending: false })

    if (docType) query = query.eq('doc_type', docType)

    const { data, error } = await query
    if (error) throw error

    return NextResponse.json({ data: data || [] })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Error' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  const admin = createAdminSupabaseClient()

  try {
    // Accept webhook secret for agent-generated docs
    const webhookSecret = request.headers.get('X-Buildos-Secret')
    const isInternalCall = webhookSecret && webhookSecret === process.env.N8N_WEBHOOK_SECRET

    let userId = 'system'
    let supabase: any = null

    if (!isInternalCall) {
      supabase = await createServerSupabaseClient()
      const { data: { user }, error: authError } = await supabase.auth.getUser()
      if (authError || !user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
      }
      userId = user.id
    }

    const body = await request.json()
    const {
      project_id,
      doc_type = 'other',
      title,
      content,
      owner_agent_role,
      supersede_id,   // ID of document this supersedes
    } = body

    if (!project_id || !title?.trim()) {
      return NextResponse.json({ error: 'project_id and title are required' }, { status: 400 })
    }

    if (!ALLOWED_DOC_TYPES.includes(doc_type)) {
      return NextResponse.json(
        { error: `doc_type must be one of: ${ALLOWED_DOC_TYPES.join(', ')}` },
        { status: 400 }
      )
    }

    // Determine version number (increment if superseding)
    let version = 1
    if (supersede_id) {
      const { data: old } = await admin
        .from('documents')
        .select('id, version')
        .eq('id', supersede_id)
        .single()

      if (old) {
        version = (old.version || 1) + 1
        // Mark old doc as superseded
        await admin
          .from('documents')
          .update({ status: 'superseded', superseded_by: null }) // Will be set after insert
          .eq('id', supersede_id)
      }
    }

    const { data: doc, error: docError } = await admin
      .from('documents')
      .insert({
        project_id,
        doc_type,
        title: title.trim(),
        content: content || null,
        status: 'draft',
        version,
        owner_agent_role: owner_agent_role || null,
        created_by: userId,
      })
      .select()
      .single()

    if (docError) throw new Error(docError.message)

    // Link superseded doc to new doc
    if (supersede_id) {
      await admin
        .from('documents')
        .update({ superseded_by: doc.id })
        .eq('id', supersede_id)
    }

    await writeAuditLog(admin, {
      event_type: 'document_created',
      actor_user_id: userId === 'system' ? undefined : userId,
      actor_agent_role: owner_agent_role,
      project_id,
      resource_type: 'document',
      resource_id: doc.id,
      new_value: { title: doc.title, doc_type, version },
    })

    return NextResponse.json({ data: doc }, { status: 201 })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Internal server error' }, { status: 500 })
  }
}

// PATCH /api/documents?id= — update content / status
export async function PATCH(request: NextRequest) {
  const admin = createAdminSupabaseClient()

  try {
    const supabase = await createServerSupabaseClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const docId = searchParams.get('id')
    if (!docId) {
      return NextResponse.json({ error: 'id required as ?id=' }, { status: 400 })
    }

    const body = await request.json()
    const allowed = ['title', 'content', 'status']
    const updates: Record<string, unknown> = {}
    for (const key of allowed) {
      if (key in body) updates[key] = body[key]
    }

    if (Object.keys(updates).length === 0) {
      return NextResponse.json({ error: 'No valid fields to update' }, { status: 400 })
    }

    const { data: doc, error } = await admin
      .from('documents')
      .update(updates)
      .eq('id', docId)
      .select()
      .single()

    if (error || !doc) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    return NextResponse.json({ data: doc })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Error' }, { status: 500 })
  }
}
