/**
 * POST /api/mock/agent-run
 * Development-only mock agent execution.
 * Simulates an agent completing a task without real AI/n8n.
 * ONLY active when NODE_ENV !== 'production'.
 *
 * Body: { task_id }
 * - Dispatches the task
 * - Waits 500ms
 * - Submits a mock agent output → moves task to awaiting_review
 * - Optionally auto-approves QA verdict
 */

import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient, createAdminSupabaseClient } from '@/lib/supabase/server'
import { randomUUID } from 'crypto'

const MOCK_OUTPUTS: Record<string, unknown> = {
  code: {
    files: [
      { path: 'src/feature.ts', content: '// Auto-generated by Build OS mock agent\nexport function feature() { return true; }' }
    ],
    language: 'typescript',
    summary: 'Mock code implementation generated',
    tests_included: false,
  },
  document: {
    content: '# Mock Document\n\nThis document was auto-generated by the Build OS mock agent during development.\n\n## Summary\nTask completed successfully.\n\n## Details\nAll acceptance criteria have been verified.',
    format: 'markdown',
    word_count: 42,
  },
  schema: {
    tables: [
      { name: 'mock_table', columns: [{ name: 'id', type: 'uuid', primary_key: true }] }
    ],
    migration_sql: '-- Mock migration\nCREATE TABLE IF NOT EXISTS mock_table (id uuid PRIMARY KEY);',
  },
  test: {
    test_cases: [
      { name: 'should pass basic check', passed: true, duration_ms: 12 },
      { name: 'should handle edge case', passed: true, duration_ms: 8 },
    ],
    coverage_pct: 85,
    passed: 2,
    failed: 0,
  },
  review: {
    findings: [
      { severity: 'info', message: 'Mock review: no issues found', location: null }
    ],
    approved: true,
    overall_score: 9,
  },
  qa_verdict: {
    passed: true,
    checks: [
      { name: 'Functionality', passed: true, notes: 'Mock: All checks passed' },
      { name: 'Security',      passed: true, notes: 'Mock: No issues found' },
      { name: 'Performance',   passed: true, notes: 'Mock: Within thresholds' },
    ],
    overall_notes: 'Mock QA verdict — auto-approved in development mode',
  },
}

function getMockOutput(taskType: string) {
  return MOCK_OUTPUTS[taskType] || MOCK_OUTPUTS['document']
}

export async function POST(request: NextRequest) {
  // Block in production
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Mock agent not available in production' }, { status: 403 })
  }

  const admin = createAdminSupabaseClient()

  try {
    const supabase = await createServerSupabaseClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { task_id, auto_qa = true } = body

    if (!task_id) {
      return NextResponse.json({ error: 'task_id is required' }, { status: 400 })
    }

    // Fetch task
    const { data: task } = await admin
      .from('tasks')
      .select('id, title, status, agent_role, task_type, project_id')
      .eq('id', task_id)
      .single()

    if (!task) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 })
    }

    // Step 1: Mark as ready if pending
    if (task.status === 'pending') {
      await admin.from('tasks').update({ status: 'ready' }).eq('id', task_id)
    }

    // Step 2: Create task_run
    const taskRunId = randomUUID()
    await admin.from('task_runs').insert({
      id: taskRunId,
      task_id: task.id,
      run_number: 1,
      status: 'running',
      agent_role: task.agent_role,
      started_at: new Date().toISOString(),
      triggered_by: user.id,
    })

    // Step 3: Mark as in_progress
    await admin.from('tasks').update({
      status: 'in_progress',
      dispatched_at: new Date().toISOString(),
    }).eq('id', task_id)

    // Step 4: Simulate agent execution — call our own /api/agent/output
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'
    const mockOutput = getMockOutput(task.task_type || 'document')
    const mockCostUsd = 0.0025 + Math.random() * 0.005 // ~$0.002–$0.007

    const agentOutputPayload = {
      task_id: task.id,
      task_run_id: taskRunId,
      agent_role: task.agent_role,
      output_type: task.task_type || 'document',
      output: mockOutput,
      success: true,
      tokens_used: Math.floor(800 + Math.random() * 1200),
      model_id: 'mock-agent-v1',
      cost_usd: Math.round(mockCostUsd * 100000) / 100000,
      idempotency_key: `mock:agent_output:${taskRunId}`,
    }

    const outputRes = await fetch(`${appUrl}/api/agent/output`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Buildos-Secret': process.env.N8N_WEBHOOK_SECRET || 'dev-secret',
      },
      body: JSON.stringify(agentOutputPayload),
    })

    if (!outputRes.ok) {
      const err = await outputRes.json()
      return NextResponse.json({ error: 'Agent output submission failed', details: err }, { status: 500 })
    }

    // Step 5: Auto-QA if requested
    let qaResult = null
    if (auto_qa) {
      // Wait a moment then submit QA verdict
      await new Promise(r => setTimeout(r, 200))

      const qaPayload = {
        task_id: task.id,
        verdict: 'pass',
        checks: [
          { name: 'Output schema valid',  passed: true, notes: 'Mock check passed' },
          { name: 'No security issues',   passed: true, notes: 'Mock check passed' },
          { name: 'Meets acceptance criteria', passed: true, notes: 'Mock check passed' },
        ],
        notes: 'Auto-approved by mock agent in development mode',
        agent_role: 'qa_security_auditor',
        idempotency_key: `mock:qa:${task_id}:${Date.now()}`,
      }

      const qaRes = await fetch(`${appUrl}/api/qa/verdict`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Cookie': request.headers.get('cookie') || '',
        },
        body: JSON.stringify(qaPayload),
      })

      if (qaRes.ok) {
        qaResult = await qaRes.json()
      }
    }

    return NextResponse.json({
      data: {
        task_id,
        task_run_id: taskRunId,
        final_status: auto_qa ? 'completed' : 'awaiting_review',
        cost_usd: agentOutputPayload.cost_usd,
        tokens_used: agentOutputPayload.tokens_used,
        qa_auto_approved: auto_qa,
        mode: 'mock',
      }
    })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Error' }, { status: 500 })
  }
}
