// src/lib/wizard-readiness.ts
// BuildOS P0 — Generated by pipeline validation
// This file was written by the code generation pipeline

import { createAdminSupabaseClient } from '@/lib/supabase/server'

export type ReadinessField = {
  key: string
  weight: number
  minLength: number
}

export const READINESS_FIELDS: ReadinessField[] = [
  { key: 'product_name',    weight: 15, minLength: 3 },
  { key: 'target_audience', weight: 20, minLength: 10 },
  { key: 'core_problem',    weight: 25, minLength: 20 },
  { key: 'key_features',    weight: 20, minLength: 15 },
  { key: 'monetisation',    weight: 10, minLength: 3 },
  { key: 'timeline_weeks',  weight: 5,  minLength: 1 },
  { key: 'budget_usd',      weight: 5,  minLength: 1 },
]

export function calculateReadiness(fields: Record<string, string>): number {
  let score = 0
  for (const { key, weight, minLength } of READINESS_FIELDS) {
    const val = (fields[key] || '').trim()
    if (val.length >= minLength) score += weight
  }
  return score
}
